services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8000
